site_name: 中文语义依存图标注规范

nav:
- 主页: 'index.md'
- 标注概述:  '语义依存图标注概述'
- 语义关系: '语义关系概述'
- 中枢论元: '中枢论元的标注细则'
- 周边角色: '语义周边角色标注细则'
- 结构关系:  '语义结构关系的标注细则'
- 依附标记:  '语义依附标记的标注细则'
- 特殊结构: '特殊结构标注集'
- 附录: '表格(最后）'
- 关于: 'NLPinBLCU'
theme:  
  name : mkdocs-material