site_name: 中文语义依存图标注规范
site_url : https://csdp-doc.readthedocs.io

nav:
- 引言: 'index.md'
- 标注概述:  '语义依存图标注概述'
- 语义关系: '语义关系概述'
- 中枢论元: '中枢论元的标注细则'
- 周边角色: '语义周边角色标注细则'
- 结构关系:  '语义结构关系的标注细则'
- 依附标记:  '语义依附标记的标注细则'
- 特殊结构: '特殊结构标注集'
- 结语: '结语'
- 附录: '附录'

theme:  
  name : material
  language : 'zh'
  icon:
    repo: fontawesome/brands/github-alt
edit_uri: ""

plugins:
  - search:
      separator: '[\s\-\.]+'
  - git-revision-date

google_analytics:
  - UA-G-9MMQDMK711
  - auto

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NLPInBLCU
    - icon: fontawesome/solid/paper-plane
      link: mailto:<yqshao163@163.com>
      name: contact with us
repo_url: https://github.com/NLPInBLCU/ChineseSemanticDependencyDocument
repo_name: CSDP-doc

markdown_extensions:
  - toc :
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2020 - 2021 Institute of Applied Linguistics, Beijing Language and Culture University, All rights reserved

